[pytest]
testpaths = tests
addopts = --html=reports/report.html --self-contained-html -v
markers =
    smoke: Smoke tests
    regression: Regression tests
    dynamic_elements: Tests for dynamic web elements
    ajax: Tests for AJAX calls
    frames: Tests for frames and iframes
    alerts: Tests for pop-ups and alerts
